import { ARMA, COLOR, INSTOCK, LEVEL } from "../../type";

const fuciliData = [
  {
    code: "F-000",
    img: "https://i.ibb.co/7CX5Zdv/F-000-0.jpg",
    imgs: [
      "https://i.ibb.co/7CX5Zdv/F-000-0.jpg",
      "https://i.ibb.co/XxMsVZ/F-000-1.jpg",
      "https://i.ibb.co/df7v7sQ/F-000-2.jpg",
      "https://i.ibb.co/hYtdYMg/F-000-3.jpg",
      "https://i.ibb.co/nnYYdSR/F-000-4.jpg",
      "https://i.ibb.co/kxNfKxm/F-000-5.jpg",
      "https://i.ibb.co/8sXMxwy/F-000-6.jpg",
    ],
    title: "CM.076A Full Metal [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 240,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-001",
    img: "https://i.ibb.co/3fS3ZNB/F-001-0.jpg",
    imgs: [
      "https://i.ibb.co/3fS3ZNB/F-001-0.jpg",
      "https://i.ibb.co/kgn2WK3/F-001-2.jpg",
      "https://i.ibb.co/d2mnHby/F-001-4.jpg",
      "https://i.ibb.co/MZ6wqFH/F-001-1.jpg",
      "https://i.ibb.co/8sCHMh1/F-001-3.jpg",
      "https://i.ibb.co/Y0mFBGX/F-001-5.jpg",
      "https://i.ibb.co/sb2BtkD/F-001-6.jpg",
    ],
    title: "CM.650A Mosfet Edition [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 180,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-002a",
    img: "https://i.ibb.co/SxcFdv9/F-002a-1.jpg",
    imgs: [
      "https://i.ibb.co/RQ7JMJ9/F-002a-2.jpg",
      "https://i.ibb.co/j3LW35p/F-002a-0.jpg",
      "https://i.ibb.co/SxcFdv9/F-002a-1.jpg",
      "https://i.ibb.co/KzjyGM2/F-002a-4.jpg",
      "https://i.ibb.co/hc8CJjX/F-002a-3.jpg",
      "https://i.ibb.co/SJjNYy9/F-002a-5.jpg",
      "https://i.ibb.co/T4vTRhq/F-002a-6.jpg",
    ],
    title: "M904C Fire Control System Edition [DE]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 220,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: "F-002b",
  },
  {
    code: "F-002b",
    img: "https://i.ibb.co/JtC2zLH/F-002b-0.jpg",
    imgs: [
      "https://i.ibb.co/sVR5FxL/F-002b-3.jpg",
      "https://i.ibb.co/QffC7Bt/F-002b-1.jpg",
      "https://i.ibb.co/tZJ5J7g/F-002b-4.jpg",
      "https://i.ibb.co/qWJvd1V/F-002b-5.jpg",
      "https://i.ibb.co/b5hMrNC/F-002b-6.jpg",
      "https://i.ibb.co/JtC2zLH/F-002b-0.jpg",
      "https://i.ibb.co/v39hYD9/F-002b-2.jpg",
    ],
    title: "M904R Fire Control System Edition [DE]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 220,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: "F-002a",
  },
  {
    code: "F-003",
    img: "https://i.ibb.co/2gLqjtF/F-003-0.jpg",
    imgs: [
      "https://i.ibb.co/4KNT9xT/F-003-1.jpg",
      "https://i.ibb.co/XsPvJjW/F-003-3.jpg",
      "https://i.ibb.co/MPr2DrX/F-003-4.jpg",
      "https://i.ibb.co/2gLqjtF/F-003-0.jpg",
      "https://i.ibb.co/5TssnWs/F-003-2.jpg",
      "https://i.ibb.co/KwL93GM/F-003-5.jpg",
      "https://i.ibb.co/p1xWzBk/F-003-6.jpg",
    ],
    title: "M904G Fire Control System Edition [DE]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 190,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-004",
    img: "https://i.ibb.co/KDyfS0L/F-004-1.jpg",
    imgs: [
      "https://i.ibb.co/RTH18Xr/F-004-3.jpg",
      "https://i.ibb.co/KDyfS0L/F-004-1.jpg",
      "https://i.ibb.co/gP1cS77/F-004-0.jpg",
      "https://i.ibb.co/s25KkX8/F-004-4.jpg",
      "https://i.ibb.co/xXyd3YZ/F-004-2.jpg",
      "https://i.ibb.co/XFt5FZC/F-004-5.jpg",
      "https://i.ibb.co/x6sRTtN/F-004-6.jpg",
    ],
    title: "CM.366M Tactical Full Metal [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 175,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-005",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "608-SL84 [J.G.Works]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 210,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-006",
    img: "https://i.ibb.co/7CX5Zdv/F-000-0.jpg",
    imgs: [
      "https://i.ibb.co/Kbt3Y0N/F-006-2.jpg",
      "https://i.ibb.co/mRDBYsG/F-006-0.jpg",
      "https://i.ibb.co/nLcmq2S/F-006-4.jpg",
      "https://i.ibb.co/Btkf69K/F-006-1.jpg",
      "https://i.ibb.co/R6CCyFS/F-006-3.jpg",
      "https://i.ibb.co/ZJRpNmF/F-006-5.jpg",
      "https://i.ibb.co/vYzG21X/F-006-6.jpg",
    ],
    title: "JG080 S-550 [J.G.Works]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 200,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-007",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "CM.518 [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 110,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-008",
    img: "https://i.ibb.co/zNvbHbw/F-008-0.jpg",
    imgs: [
      "https://i.ibb.co/1mJpbBb/F-008-1.jpg",
      "https://i.ibb.co/9vpZCDf/F-008-2.jpg",
      "https://i.ibb.co/zNvbHbw/F-008-0.jpg",
      "https://i.ibb.co/288kJk7/F-008-4.jpg",
      "https://i.ibb.co/HNQ8RJw/F-008-3.jpg",
      "https://i.ibb.co/z47Y7Vg/F-008-5.jpg",
      "https://i.ibb.co/jvhMDJY/F-008-6.jpg",
    ],
    title: "CM.619 - Black [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 170,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-009",
    img: "https://i.ibb.co/jvkJQB9/F-009-0.jpg",
    imgs: [
      "https://i.ibb.co/7nFbpCd/F-009-3.jpg",
      "https://i.ibb.co/gjR5ZfH/F-009-1.jpg",
      "https://i.ibb.co/4J2HZ72/F-009-4.jpg",
      "https://i.ibb.co/jvkJQB9/F-009-0.jpg",
      "https://i.ibb.co/PGMdq67/F-009-2.jpg",
      "https://i.ibb.co/r0wqcfz/F-009-5.jpg",
      "https://i.ibb.co/b3vVcgN/F-009-6.jpg",
    ],
    title: "CM.356 Tactical - Black [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 90,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-010",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "CM.706 - Olive [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 160,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-011",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "MB4420 - Black [WELL]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-012",
    img: "https://i.ibb.co/k0LhvPN/F-012-0.jpg",
    imgs: [
      "https://i.ibb.co/c1dHDvv/F-012-1.jpg",
      "https://i.ibb.co/k0LhvPN/F-012-0.jpg",
      "https://i.ibb.co/0Y0WS0h/F-012-2.jpg",
      "https://i.ibb.co/Gcgp91r/F-012-3.jpg",
      "https://i.ibb.co/5cqfVj3/F-012-5.jpg",
      "https://i.ibb.co/qYHbG3B/F-012-4.jpg",
      "https://i.ibb.co/58XZZVy/F-012-6.jpg",
    ],
    title: "ARP 9",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 230,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-013",
    img: "https://i.ibb.co/BBQ4CQn/F-013-0.jpg",
    imgs: [
      "https://i.ibb.co/YL7Mgkk/F-013-5.jpg",
      "https://i.ibb.co/SfG4HNr/F-013-6.jpg",
      "https://i.ibb.co/JRdQL6z/F-013-1.jpg",
      "https://i.ibb.co/bgYspJx/F-013-3.jpg",
      "https://i.ibb.co/BBQ4CQn/F-013-0.jpg",
      "https://i.ibb.co/XzxvC9q/F-013-4.jpg",
      "https://i.ibb.co/Vtmq5v7/F-013-2.jpg",
    ],
    title: "Evolution LA M4 Carbine Foliage Green Lone Star Edition",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 320,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-014",
    img: "https://i.ibb.co/ry05RNr/F-014-0.jpg",
    imgs: [
      "https://i.ibb.co/2KZZT5g/F-014-2.jpg",
      "https://i.ibb.co/x5yyDPy/F-014-1.jpg",
      "https://i.ibb.co/mSpHJGx/F-014-3.jpg",
      "https://i.ibb.co/ry05RNr/F-014-0.jpg",
      "https://i.ibb.co/DgQ3Bw1/F-014-4.jpg",
      "https://i.ibb.co/xM6NLpm/F-014-5.jpg",
      "https://i.ibb.co/5RxkWQL/F-014-6.jpg",
    ],
    title: "Evolution Ghost M EMR A Carbontech ETU",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 220,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-015",
    img: "https://i.ibb.co/k3pMSbC/F-015-0.jpg",
    imgs: [
      "https://i.ibb.co/dPLL5bk/F-015-1.jpg",
      "https://i.ibb.co/wgg6dkS/F-015-3.jpg",
      "https://i.ibb.co/MfP1rn5/F-015-4.jpg",
      "https://i.ibb.co/RyCVg0R/F-015-5.jpg",
      "https://i.ibb.co/sJc0fRv/F-015-6.jpg",
      "https://i.ibb.co/k3pMSbC/F-015-0.jpg",
      "https://i.ibb.co/2605wD9/F-015-2.jpg",
    ],
    title: "ARP 556",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 320,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-016",
    img: "https://i.ibb.co/55q8GLp/F-016-0.jpg",
    imgs: [
      "https://i.ibb.co/xjRVSps/F-016-6.jpg",
      "https://i.ibb.co/x5Y44BR/F-F-016-5.jpg",
      "https://i.ibb.co/VjKgLVT/F-016-1.jpg",
      "https://i.ibb.co/nC0Y5yd/F-016-3.jpg",
      "https://i.ibb.co/7vbP3CV/F-016-4.jpg",
      "https://i.ibb.co/55q8GLp/F-016-0.jpg",
      "https://i.ibb.co/LhyJ95B/F-016-2.jpg",
    ],
    title: "M5 SD5 w/ ",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 130,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-017",
    img: "https://i.ibb.co/QYPjfhF/F-017-1.jpg",
    imgs: [
      "https://i.ibb.co/cQx9dpg/F-017-0.jpg",
      "https://i.ibb.co/QYPjfhF/F-017-1.jpg",
      "https://i.ibb.co/PFHwFFt/F-017-2.jpg",
      "https://i.ibb.co/KywNr3t/F-017-3.jpg",
      "https://i.ibb.co/2SwJLLw/F-017-4.jpg",
      "https://i.ibb.co/L0XpNbZ/F-017-5.jpg",
      "https://i.ibb.co/SNm0qzB/F-017-6.jpg",
    ],
    title: "Evolution Recon S 14.5 Carbontech",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-018",
    img: "https://i.ibb.co/GQ6Dhn8/F-018-0.jpg",
    imgs: [
      "https://i.ibb.co/SymNmbk/F-018-6.jpg",
      "https://i.ibb.co/vL6GHpY/F-018-5.jpg",
      "https://i.ibb.co/S3f2BdS/F-018-1.jpg",
      "https://i.ibb.co/nf0512z/F-018-3.jpg",
      "https://i.ibb.co/RYqQ85t/F-018-4.jpg",
      "https://i.ibb.co/GQ6Dhn8/F-018-0.jpg",
      "https://i.ibb.co/bJVvhpr/F-018-2.jpg",
    ],
    title: "Evolution Recon S SOPMOD Carbontech",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-019",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "Evolution Ghost XS EMR Carbontech ETU",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 180,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-020",
    img: "https://i.ibb.co/ftK5jkW/F-020-0.jpg",
    imgs: [
      "https://i.ibb.co/ZfKBqCg/F-020-5.jpg",
      "https://i.ibb.co/NN8ctJ4/F-020-6.jpg",
      "https://i.ibb.co/Fzfs5cv/F-020-1.jpg",
      "https://i.ibb.co/QJpgHhY/F-020-3.jpg",
      "https://i.ibb.co/tLkx1kb/F-020-4.jpg",
      "https://i.ibb.co/ftK5jkW/F-020-0.jpg",
      "https://i.ibb.co/jvcgR8w/F-020-2.jpg",
    ],
    title: "Evolution Ghost XS EMR PDW Carbontech ETU",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 220,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-021",
    img: "https://i.ibb.co/YbyS64m/F-021-0.jpg",
    imgs: [
      "https://i.ibb.co/2hMB1c4/F-021-6.jpg",
      "https://i.ibb.co/w4thMGf/F-021-5.jpg",
      "https://i.ibb.co/Yc1L8JX/F-021-1.jpg",
      "https://i.ibb.co/2vH4W54/F-021-3.jpg",
      "https://i.ibb.co/Rbrz5SQ/F-021-4.jpg",
      "https://i.ibb.co/YbyS64m/F-021-0.jpg",
      "https://i.ibb.co/FzVftyM/F-021-2.jpg",
    ],
    title: "Evolution Ghost S EMR S Carbontech ETU",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 220,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-022",
    img: "https://i.ibb.co/GQ5XtmV/F-022-0.jpg",
    imgs: [
      "https://i.ibb.co/mSVpxBd/F-022-6.jpg",
      "https://i.ibb.co/c66VgMJ/F-022-5.jpg",
      "https://i.ibb.co/BNjs279/F-022-1.jpg",
      "https://i.ibb.co/v3z0HxG/F-022-3.jpg",
      "https://i.ibb.co/xCHPMBC/F-022-4.jpg",
      "https://i.ibb.co/GQ5XtmV/F-022-0.jpg",
      "https://i.ibb.co/wsXf4Z6/F-022-2.jpg",
    ],
    title: "Evolution Ghost S EMR PDW Carbontech ETU",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 250,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-029",
    img: "https://i.ibb.co/022nDk1/F-029-0.jpg",
    imgs: [
      "https://i.ibb.co/NCTgJKv/F-029-5.jpg",
      "https://i.ibb.co/F38PMqx/F-029-6.jpg",
      "https://i.ibb.co/8X1Rwy8/F-029-2.jpg",
      "https://i.ibb.co/022nDk1/F-029-0.jpg",
      "https://i.ibb.co/kKJgvfQ/F-029-1.jpg",
      "https://i.ibb.co/pv7mcCk/F-029-3.jpg",
      "https://i.ibb.co/Xpgrbzd/F-029-4.jpg",
    ],
    title: "DBOYS 2.0 M4 KEYMOD 10'' COMMANDO MARINE DARK EARTH",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 180,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-031",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "AK 47 bicolor cyma",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 120,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-032",
    img: "https://i.ibb.co/mzm4ktF/F-032-0.jpg",
    imgs: [
      "https://i.ibb.co/tmjgPY9/F-032-2.jpg",
      "https://i.ibb.co/mzm4ktF/F-032-0.jpg",
      "https://i.ibb.co/c2CS1f9/F-032-5.jpg",
      "https://i.ibb.co/KD4zHg5/F-032-6.jpg",
      "https://i.ibb.co/BTNtMPB/F-032-1.jpg",
      "https://i.ibb.co/Vj5FpjG/F-032-3.jpg",
      "https://i.ibb.co/q55jCvV/F-032-4.jpg",
    ],
    title: "CM 515 cyma m4",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 140,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-033",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "ASR120 RED DRAGON ESILVER EDITION [APS]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 380,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-034",
    img: "https://i.ibb.co/9VxPLwf/F-034-0.jpg",
    imgs: [
      "https://i.ibb.co/fYYkHyN/F-034-5.jpg",
      "https://i.ibb.co/9p8m42Y/F-034-6.jpg",
      "https://i.ibb.co/9qxPyJv/F-034-1.jpg",
      "https://i.ibb.co/j344JbQ/F-034-3.jpg",
      "https://i.ibb.co/kKGpcrz/F-034-4.jpg",
      "https://i.ibb.co/9VxPLwf/F-034-0.jpg",
      "https://i.ibb.co/XVGrsGy/F-034-2.jpg",
    ],
    title: "STUBBY M4",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-035",
    img: "https://i.ibb.co/r58qNsv/F-035-0.jpg",
    imgs: [
      "https://i.ibb.co/85p2T7r/F-035-6.jpg",
      "https://i.ibb.co/1Zqc8dc/F-035-5.jpg",
      "https://i.ibb.co/bLJvXmf/F-035-1.jpg",
      "https://i.ibb.co/1sYRv5r/F-035-3.jpg",
      "https://i.ibb.co/yg0BL9s/F-035-4.jpg",
      "https://i.ibb.co/r58qNsv/F-035-0.jpg",
      "https://i.ibb.co/wC1bjnC/F-035-2.jpg",
    ],
    title: "ICS FUCILE ELETTRICO CS4A1 TAN",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 210,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-017",
    img: "https://i.ibb.co/QYPjfhF/F-017-1.jpg",
    imgs: [
      "https://i.ibb.co/cQx9dpg/F-017-0.jpg",
      "https://i.ibb.co/QYPjfhF/F-017-1.jpg",
      "https://i.ibb.co/PFHwFFt/F-017-2.jpg",
      "https://i.ibb.co/KywNr3t/F-017-3.jpg",
      "https://i.ibb.co/2SwJLLw/F-017-4.jpg",
      "https://i.ibb.co/L0XpNbZ/F-017-5.jpg",
      "https://i.ibb.co/SNm0qzB/F-017-6.jpg",
    ],
    title: "Evolution Recon S 14.5 Carbontech",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-036",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "M4A1 CQB FOLDING",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 350,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-037",
    img: "https://i.ibb.co/yyfgD1p/F-037-0.jpg",
    imgs: [
      "https://i.ibb.co/kXf5QxC/F-037-6.jpg",
      "https://i.ibb.co/xfK0dy6/F-037-5.jpg",
      "https://i.ibb.co/vqKXhp7/F-037-1.jpg",
      "https://i.ibb.co/txk6n0s/F-037-3.jpg",
      "https://i.ibb.co/7K1g9BM/F-037-4.jpg",
      "https://i.ibb.co/xFZz7x1/F-037-2.jpg",
      "https://i.ibb.co/yyfgD1p/F-037-0.jpg",
    ],
    title: "AR M4 ",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 210,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-038",
    img:
      "http://wwwnew.oa-abruzzo.inaf.it/wp-content/uploads/2017/02/work_in_progress.png",
    imgs: [],
    title: "FUCILE DI PRECISIONE COLOR LEGNO",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 110,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.No,
    variante: null,
  },
  {
    code: "F-039",
    img: "https://i.ibb.co/QdpNNQB/F-039-0.jpg",
    imgs: [
      "https://i.ibb.co/kqYLRry/F-039-6.jpg",
      "https://i.ibb.co/jbgPKpd/F-039-5.jpg",
      "https://i.ibb.co/RHjtngD/F-039-2.jpg",
      "https://i.ibb.co/QdpNNQB/F-039-0.jpg",
      "https://i.ibb.co/wpZCkVd/F-039-4.jpg",
      "https://i.ibb.co/xJ5ttTf/F-039-1.jpg",
      "https://i.ibb.co/3N4Nwxp/F-039-3.jpg",
    ],
    title: "APS FUCILE ELETTRICO ASR118 RS-2 BOAR TACT",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 350,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-040",
    img: "https://i.ibb.co/txQQ146/F-040-0.jpg",
    imgs: [
      "https://i.ibb.co/jV9Tn12/F-040-5.jpg",
      "https://i.ibb.co/jhR3Z79/F-040-6.jpg",
      "https://i.ibb.co/kQGdb2n/F-040-1.jpg",
      "https://i.ibb.co/c68dfpv/F-040-3.jpg",
      "https://i.ibb.co/T25pRqL/F-040-4.jpg",
      "https://i.ibb.co/txQQ146/F-040-0.jpg",
      "https://i.ibb.co/sPmBXmn/F-040-2.jpg",
    ],
    title: "CM.506 [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 140,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: null,
  },
  {
    code: "F-041",
    img: "https://i.ibb.co/0rWnrVr/F-041-0.jpg",
    imgs: [
      "https://i.ibb.co/b6byKgd/F-041-5.jpg",
      "https://i.ibb.co/SfqCrzF/F-041-6.jpg",
      "https://i.ibb.co/LgJjncJ/F-041-1.jpg",
      "https://i.ibb.co/rH3MYzv/F-041-3.jpg",
      "https://i.ibb.co/rcjyW8L/F-041-4.jpg",
      "https://i.ibb.co/0rWnrVr/F-041-0.jpg",
      "https://i.ibb.co/CKDBkwb/F-041-2.jpg",
    ],
    title: "CM.612 - DARK EARTH [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: "F-042",
  },
  {
    code: "F-042",
    img: "https://i.ibb.co/qWhGvst/F-042-0.jpg",
    imgs: [
      "https://i.ibb.co/ZNjwRxj/F-042-5.jpg",
      "https://i.ibb.co/D8gpDFg/F-042-6.jpg",
      "https://i.ibb.co/qWhGvst/F-042-0.jpg",
      "https://i.ibb.co/FXCq9YQ/F-042-2.jpg",
      "https://i.ibb.co/r0XJJnm/F-042-4.jpg",
      "https://i.ibb.co/kSmrfdm/F-042-1.jpg",
      "https://i.ibb.co/Pm1G3Th/F-042-3.jpg",
    ],
    title: "CM.612 - BLACK [CYMA]",
    type: ARMA.FUCILE,
    level: LEVEL.FASCIA_BASSA,
    colour: COLOR.BLACK,
    price: 150,
    description: "Descrizione",
    fullDescription: "Full descrizione",
    inStock: INSTOCK.Si,
    variante: "F-041",
  },
];

export default fuciliData;
