const fuciliData = [
  {
    code: "F-000_0",
    img: "https://i.ibb.co/7CX5Zdv/F-000-0.jpg",
    title: "F-000",
    type: "fucile",
    price: 130,
    description: "Descrizione",
    inStock: true,
  },
  {
    code: "F-000_1",
    img: "https://i.ibb.co/kXxMsVZ/F-000-1.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-000_2",
    img: "https://i.ibb.co/df7v7sQ/F-000-2.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-000_3",
    img: "https://i.ibb.co/hYtdYMg/F-000-3.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-000_4",
    img: "https://i.ibb.co/nnYYdSR/F-000-4.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-000_5",
    img: "https://i.ibb.co/kxNfKxm/F-000-5.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-000_6",
    img: "https://i.ibb.co/8sXMxwy/F-000-6.jpg",
    title: "F-000",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_0",
    img: "https://i.ibb.co/cQx9dpg/F-001-0.jpg",
    title: "F-001",
    type: "fucile",
    price: 130,
    description: "Descrizione",
    inStock: true,
  },
  {
    code: "F-001_1",
    img: "https://i.ibb.co/QYPjfhF/F-001-1.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_2",
    img: "https://i.ibb.co/PFHwFFt/F-001-2.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_3",
    img: "https://i.ibb.co/KywNr3t/F-001-3.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_4",
    img: "https://i.ibb.co/2SwJLLw/F-001-4.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_5",
    img: "https://i.ibb.co/L0XpNbZ/F-001-5.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
  {
    code: "F-001_6",
    img: "https://i.ibb.co/SNm0qzB/F-001-6.jpg",
    title: "F-001",
    type: "fucile",
    price: 100,
    description: "Description",
    inStock: true,
  },
];

export default fuciliData;
